#!/usr/bin/env bash
set -e

if test $# -ne 2; then
	echo "Usage: $0 target/debug/shellharden moduletests/"
	exit 1
fi
exe="$1"
dir="$2"

pass=()
fail=()
for i in "${dir%/}"/original/*; do
	expect="${i%/original/*}/expected/${i##*/}"
	if diff=$(diff -u "$expect" <("$exe" --transform "$i" 2>&1)); then
		pass+=("$i")
	else
		fail+=("$i")
		printf '\n——— \e[1m%s\e[m ———\n%s\n' "$i" "$diff"
	fi
done

echo
echo Passes:
printf '\t\e[32m%s\e[m\n' "${pass[@]}"

echo
echo Fails:
printf '\t\e[31m%s\e[m\n' "${fail[@]}"

exit ${#fail[@]}
