#!/usr/bin/env bash
set -e

if test $# -ne 2; then
	echo "Usage: $0 target/debug/shellharden moduletests/"
	exit 1
fi
exe="$1"
dir="$2"

pass=()
fail=()
expect(){
	local original=$1
	local expected=$2
	if diff=$(diff -u -- "$expected" <("$exe" --transform -- "$original" 2>&1)); then
		pass+=("$original")
	else
		fail+=("$original")
		printf '\n——— \e[1m%s\e[m ———\n%s\n' "$original" "$diff"
	fi
}

for i in "${dir%/}"/original/*; do
	expect "$i" "${i%/original/*}/expected/${i##*/}"
done

for i in "${dir%/}"/expected/*; do
	case ${i##*/} in
		error_*|unsupp_*)
			continue
		;;
	esac
	expect "$i" "$i"
done
expect "$0" "$0"

echo
echo Passes:
printf '\t\e[32m%s\e[m\n' "${pass[@]}"

echo
echo Fails:
printf '\t\e[31m%s\e[m\n' "${fail[@]}"

exit ${#fail[@]}
